#!/usr/bin/env bash



# Import Current Theme
DIR="$HOME/.config/rofi"
STYLE="spark"
RASI="$DIR/themes/$STYLE/rofi/askpass.rasi"

# rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -theme ${RASI}
